#!/usr/bin/env python3
"""
This script will process a json file containing data for the car sales. It will read the file and process the data, generating a few summary lines regarding
highest revenue, highest total sales, and year with the best total sales.

Then a PDF report will be created using the json file data and then sent as an attachment via email.

Note: This script will import two modules to generate the pdf and send the email as an attachment.

"""

import json
import locale
import sys
import os
from pathlib import Path
import reports
import emails
from dotenv import load_dotenv

def load_data(filename):
  """Loads the contents of filename as a JSON file."""
  with open(filename) as json_file:
    data = json.load(json_file)  #  (file --> python object): de-serializes the json file into a python object (list of dictionary)
  return data


def format_car(car):
  """Given a car dictionary, returns a nicely formatted name."""
  return "{} {} ({})".format(car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
  """Analyzes the data, looking for maximums.

  Returns a list of lines that summarize the information.
  """
  max_revenue = {"revenue": 0}   # track the current maximum revenue and replace when newer max value found
  track_sales = {"total_sales":0}  # track the current maximum total_sales and replace when newer max value found
  yearly_sales = {}   # tally the sales number and group by years.
  for item in data:
    # Calculate the revenue generated by this model (price * total_sales)
    # We need to convert the price from "$1234.56" to 1234.56
    item_price = locale.atof(item["price"].strip("$"))   # locala.atof() is a way to format a string of numbers into a float type
    item_revenue = item["total_sales"] * item_price
    car_year = item['car']['car_year']
    total_sale = item['total_sales']
    if item_revenue > max_revenue["revenue"]:  # is the calculated revenue greater than the current maximum revenue?
      item["revenue"] = item_revenue   # item["revenue"] is added to the data item
      max_revenue = item   # max_revenue now contains the data item with newly added revenue and amount
    # TODO: also handle max sales
    if item['total_sales'] > track_sales['total_sales']:  # get the total sales from data item, compare greater than current highest total_sales
      track_sales['total_sales'] = item['total_sales']    # make the new total sales the current highest total sales
      highest_sale = item                                 # save the data item to extract car data for creating summary
    # TODO: also handle most popular car_year
    if car_year not in yearly_sales:       # check dictionary for key value
      yearly_sales[car_year] = total_sale   # add if not in dictionary wth total sales for that year
    else:
      yearly_sales[car_year] += total_sale   # increment by additional total sales if already in dictionary
  highest_sale_year = max(yearly_sales.items(), key=lambda item: item[1])  # where item is a key/value obtained from .items(), passed to 'lambda item:' where lambda returns item[1] as the key for max to evaluate.

  summary = [
    "The {} generated the most revenue: ${}.".format(format_car(max_revenue["car"]), max_revenue["revenue"]),
    "<br/>",                                                                                                            # add <br/> to print line breaks in pdf report so that all the lines don't appear as 1 sentence.
    "The {} had the most sales: {}.".format(format_car(highest_sale["car"]), track_sales['total_sales']),
    "<br/>",
    "The most popular year was {} with {} in sales.".format(highest_sale_year[0], highest_sale_year[1]),
    "<br/>"
]
  return summary


def cars_dict_to_table(car_data):
  """Turns the data in car_data into a list of lists."""
  table_data = [["ID", "Car", "Price", "Total Sales"]]   # header for table
  for item in car_data:
    table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
  return table_data


def main(argv):
  """Process the JSON data and generate a full report out of it."""
  data = load_data("../data/car_sales.json")
  summary = process_data(data)

  # TODO: turn this into a PDF report
  # generate(filename, title, additional_info, table_data):
  out_path = Path(__file__).parent.parent / 'outfiles'
  filename = os.path.join(out_path, "cars.pdf")
  title = "Sales Summary for last month"
  additional_info = "".join(summary)    # join a list into a string
  table_data = cars_dict_to_table(data)
  reports.generate(filename, title, additional_info, table_data)


  # TODO: send the PDF report as an email attachment
  # generate(sender, recipient, subject, body, attachment_path)
  sender = "dncooke@icloud.com"
  recipient = "damienc7@gmail.com"
  subject = "Sales summary for last month"
  body = "".join(summary).replace("<br/>", "\n")   # replace style pdf:<br/> with regular text:\n. note: PDF styling uses html style
  print(body)
  attachment_path = os.path.join(out_path, "cars.pdf")
  message = emails.generate(sender, recipient, subject, body, attachment_path)   # generate email message for sending
  emails.send(message,sender)  # sender required for user authentication to email server, not for sending email

if __name__ == "__main__":
  load_dotenv()   # get env variable for sending email. required when from dotenv import load_dotenv.
  main(sys.argv)


""" RUNTIME:

/Users/admin/PycharmProjects/PythonProject/Coursera_GoogleITAutomation_Projects/.venv/bin/python3.14 /Users/admin/PycharmProjects/PythonProject/Coursera_GoogleITAutomation_Projects/Projects_6/Auto-Generate-PDF-Send-by-Email/scripts/cars.py 
['The Mercedes-Benz E-Class (2009) generated the most revenue: $22749529.02.', '<br/>', 'The Acura Integra (1995) had the most sales: 1192.', '<br/>', 'The most popular year was 2007 with 21534 in sales.', '<br/>']
The Mercedes-Benz E-Class (2009) generated the most revenue: $22749529.02.
The Acura Integra (1995) had the most sales: 1192.
The most popular year was 2007 with 21534 in sales.

From: dncooke@icloud.com
To: damienc7@gmail.com
Subject: Sales summary for last month
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="===============6753633594020557066=="

--===============6753633594020557066==
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit

The Mercedes-Benz E-Class (2009) generated the most revenue: $22749529.02.
The Acura Integra (1995) had the most sales: 1192.
The most popular year was 2007 with 21534 in sales.

--===============6753633594020557066==
Content-Type: application/pdf
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="cars.pdf"
MIME-Version: 1.0

JVBERi0xLjQKJZOMi54gUmVwb3J0TGFiIEdlbmVyYXRlZCBQREYgZG9jdW1lbnQgKG9wZW5zb3Vy
Y2UpCjEgMCBvYmoKPDwKL0YxIDIgMCBSIC9GMiAzIDAgUgo+PgplbmRvYmoKMiAwIG9iago8PAov
QmFzZUZvbnQgL0hlbHZldGljYSAvRW5jb2RpbmcgL1dpbkFuc2lFbmNvZGluZyAvTmFtZSAvRjEg
L1N1YnR5cGUgL1R5cGUxIC9UeXBlIC9Gb250Cj4+CmVuZG9iagozIDAgb2JqCjw8Ci9CYXNlRm9u
dCAvSGVsdmV0aWNhLUJvbGQgL0VuY29kaW5nIC9XaW5BbnNpRW5jb2RpbmcgL05hbWUgL0YyIC9T
dWJ0eXBlIC9UeXBlMSAvVHlwZSAvRm9udAo+PgplbmRvYmoKNCAwIG9iago8PAovQ29udGVudHMg
MjAgMCBSIC9NZWRpYUJveCBbIDAgMCA1OTUuMjc1NiA4NDEuODg5OCBdIC9QYXJlbnQgMTkgMCBS
IC9SZXNvdXJjZXMgPDwKL0ZvbnQgMSAwIFIgL1Byb2NTZXQgWyAvUERGIC9UZXh0IC9JbWFnZUIg
L0ltYWdlQyAvSW1hZ2VJIF0KPj4gL1JvdGF0ZSAwIC9UcmFucyA8PAoKPj4gCiAgL1R5cGUgL1Bh
...
...
MyAwMDAwMCBuIAowMDAwMDI1NzM3IDAwMDAwIG4gCjAwMDAwMjgyMjYgMDAwMDAgbiAKMDAwMDAz
MDczMCAwMDAwMCBuIAowMDAwMDMzMjU3IDAwMDAwIG4gCnRyYWlsZXIKPDwKL0lEIApbPDhhYjQ1
ZjcxZTNhOTk3NzMwNWJjMDllMDNhNDY2NzA4Pjw4YWI0NWY3MWUzYTk5NzczMDViYzA5ZTAzYTQ2
NjcwOD5dCiUgUmVwb3J0TGFiIGdlbmVyYXRlZCBQREYgZG9jdW1lbnQgLS0gZGlnZXN0IChvcGVu
c291cmNlKQoKL0luZm8gMTggMCBSCi9Sb290IDE3IDAgUgovU2l6ZSAzMwo+PgpzdGFydHhyZWYK
MzU2NzMKJSVFT0YK

--===============6753633594020557066==--

Email sent successfully!

Process finished with exit code 0



"""